import { firebaseConfig } from './firebase-config.js';
import { initializeApp, getApps, getApp } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js';
import { getAuth, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js';
import { getFirestore, collection, getDocs, query, orderBy, doc, getDoc } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js';

const app=getApps().length?getApp():initializeApp(firebaseConfig);const auth=getAuth(app),db=getFirestore(app);const box=document.querySelector('#requests');
onAuthStateChanged(auth,async user=>{if(!user){location.href='../login.html';return;}try{const me=await getDoc(doc(db,'users',user.uid));if(!me.exists()||String(me.data().role).toLowerCase()!=='admin'){alert('Admin access required.');location.href='../client/dashboard.html';return;}load();}catch(e){box.innerHTML=`<div class="notice error">${esc(e.message)}</div>`;}});
async function load(){try{const snap=await getDocs(query(collection(db,'projects'),orderBy('createdAt','desc')));if(snap.empty){box.innerHTML='<div class="panel"><p class="muted">No project requests yet.</p></div>';return;}box.innerHTML='';for(const d of snap.docs){const p=d.data();const article=document.createElement('article');article.className='panel';article.innerHTML=`<span class="pill">${esc(p.status||'Pending')}</span><h2>${esc(p.name||'Untitled')}</h2><p><strong>Client:</strong> ${esc(p.clientName||'')}</p><p><strong>Email:</strong> ${esc(p.clientEmail||'')}</p><p><strong>Package:</strong> ${esc(p.package||'')}</p><p><strong>Amount:</strong> ₱${Number(p.price||0).toLocaleString('en-PH')}</p><p><strong>Payment:</strong> ${esc(p.paymentStatus||'pending')}</p><div class="admin-actions"><a class="btn" href="editor.html?id=${encodeURIComponent(d.id)}">Open Editor & Payment Verification →</a></div>`;box.appendChild(article);}}catch(e){box.innerHTML=`<div class="notice error">${esc(e.message)}</div>`;}}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
