import { firebaseConfig } from './firebase-config.js';
import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js';
import { getAuth,onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js';
import { getFirestore,doc,getDoc,setDoc,collection,serverTimestamp,updateDoc } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js';
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),id=new URLSearchParams(location.search).get('id'); const code=document.querySelector('#code'),name=document.querySelector('#fileName'),msg=document.querySelector('#editorMessage');let current='index.html';
async function guard(){const user=auth.currentUser;if(!user){location.href='../login.html';return false;}const me=await getDoc(doc(db,'users',user.uid));if(!me.exists()||me.data().role!=='admin'){alert('Admin access required.');location.href='../client/dashboard.html';return false;}return true;}
onAuthStateChanged(auth,async u=>{if(!(await guard())||!id)return;const p=await getDoc(doc(db,'projects',id));if(!p.exists()){msg.textContent='Project not found.';msg.classList.remove('hidden');return;}const files=await getDoc(doc(db,'projects',id,'files',current));if(files.exists())code.value=files.data().content||'';});
async function save(){if(!id)return;await setDoc(doc(db,'projects',id,'files',current),{name:current,content:code.value,updatedAt:serverTimestamp()},{merge:true});await updateDoc(doc(db,'projects',id),{status:'Coding',updatedAt:serverTimestamp()});msg.classList.remove('hidden');msg.textContent=current+' saved.';}
document.querySelectorAll('.file').forEach(b=>b.onclick=async()=>{await save();document.querySelectorAll('.file').forEach(x=>x.classList.remove('active'));b.classList.add('active');current=b.dataset.file;name.value=current;code.value='';const s=await getDoc(doc(db,'projects',id,'files',current));if(s.exists())code.value=s.data().content||'';});
document.querySelector('#saveCode').onclick=save;document.querySelector('#preview').onclick=()=>{const w=window.open();w.document.write(code.value);w.document.close();};document.querySelector('#deliver').onclick=async()=>{await updateDoc(doc(db,'projects',id),{status:'Completed',updatedAt:serverTimestamp()});msg.classList.remove('hidden');msg.textContent='Project marked completed.';};
