import { firebaseConfig } from './firebase-config.js';
import { initializeApp, getApps, getApp } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js';
import { getAuth, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js';
import { getFirestore, collection, addDoc, doc, setDoc, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js';

const app=getApps().length?getApp():initializeApp(firebaseConfig), auth=getAuth(app), db=getFirestore(app);
const form=document.querySelector('#requestForm'), msg=document.querySelector('#message'), designsInput=document.querySelector('#designs'), tree=document.querySelector('#tree'), selectedImages=document.querySelector('#selectedImages'), selectedPrice=document.querySelector('#selectedPrice');
let currentUser=null,nodeId=0;
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const show=(t,e=false)=>{msg.classList.remove('hidden');msg.classList.toggle('error',e);msg.textContent=t};

onAuthStateChanged(auth,async u=>{if(!u){location.href='../login.html';return}try{await u.reload()}catch{}if(!u.emailVerified){location.href='../login.html';return}currentUser=u;form.email.value=u.email||'';form.name.value=form.name.value||u.displayName||''});

function refreshParents(){
  const folders=[...tree.querySelectorAll('.tree-row[data-type="folder"]')];
  tree.querySelectorAll('.parent-select').forEach(sel=>{const old=sel.value;const own=sel.closest('.tree-row');sel.innerHTML='<option value="">Root</option>'+folders.filter(f=>f!==own).map(f=>`<option value="${f.dataset.id}">${esc(f.querySelector('.node-name').value||'Folder')}</option>`).join('');if([...sel.options].some(o=>o.value===old))sel.value=old});
}
function addNode(type,name=''){
  const id=String(++nodeId),r=document.createElement('div');r.className='tree-row';r.dataset.id=id;r.dataset.type=type;
  r.innerHTML=`<input class="node-name" value="${esc(name)}" placeholder="${type==='folder'?'folder-name':'file-name.html'}" required><textarea class="node-desc" placeholder="${type==='folder'?'Optional folder description':'Exactly what should happen in this file...'}"></textarea><select class="parent-select"><option value="">Root</option></select><button type="button" class="mini-btn danger remove">Remove</button>`;
  tree.appendChild(r);r.querySelector('.remove').onclick=()=>{r.remove();refreshParents()};r.querySelector('.node-name').oninput=refreshParents;refreshParents();return r;
}
document.querySelector('#addFolder').onclick=()=>addNode('folder');
document.querySelector('#addFile').onclick=()=>addNode('file');
addNode('file','index.html');

document.querySelectorAll('input[name="package"]').forEach(i=>i.onchange=()=>{const p=Number(i.dataset.price);selectedPrice.textContent=`Project Price: ₱${p.toLocaleString('en-PH')} • GCash Amount: ₱${p.toLocaleString('en-PH')}`});
designsInput.onchange=()=>{const f=[...designsInput.files];if(f.length>5){designsInput.value='';selectedImages.textContent='Maximum of 5 images only.'}else selectedImages.textContent=f.length?`${f.length} image(s) selected.`:''};

function compressImage(file){return new Promise((resolve,reject)=>{const rr=new FileReader();rr.onload=e=>{const im=new Image();im.onload=()=>{let w=im.width,h=im.height;if(w>1200){h=Math.round(h*1200/w);w=1200}const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(im,0,0,w,h);let q=.65,u=c.toDataURL('image/jpeg',q);while(u.length>700000&&q>.25){q-=.1;u=c.toDataURL('image/jpeg',q)}if(u.length>900000)reject(new Error(`${file.name} is too large after compression.`));else resolve({name:file.name,type:'image/jpeg',size:u.length,content:u})};im.onerror=()=>reject(new Error(`Unable to read image: ${file.name}`));im.src=e.target.result};rr.onerror=()=>reject(new Error(`Unable to load image: ${file.name}`));rr.readAsDataURL(file)})}

form.onsubmit=async e=>{e.preventDefault();if(!currentUser)return show('Please wait for your account to finish loading.',true);const p=form.querySelector('input[name="package"]:checked');if(!p)return show('Please choose a package.',true);const imgs=[...designsInput.files];if(!imgs.length||imgs.length>5)return show('Please choose 1–5 design images.',true);const structure=[...tree.querySelectorAll('.tree-row')].map(r=>({id:r.dataset.id,type:r.dataset.type,name:r.querySelector('.node-name').value.trim(),description:r.querySelector('.node-desc').value.trim(),parent:r.querySelector('.parent-select').value||null})).filter(x=>x.name);if(!structure.some(x=>x.type==='file'))return show('Add at least one file.',true);const bad=structure.find(x=>x.type==='file'&&!x.name.includes('.'));if(bad)return show(`File "${bad.name}" needs a file extension.`,true);const btn=form.querySelector('button[type="submit"]');btn.disabled=true;try{const projectName=form.website.value.trim(),clientName=form.name.value.trim(),requirements=form.requirements.value.trim(),packageName=p.value,price=Number(p.dataset.price),ref=await addDoc(collection(db,'projects'),{clientId:currentUser.uid,name:projectName,websiteName:projectName,clientName,clientEmail:currentUser.email,requirements,package:packageName,price,paymentMethod:'GCash',paymentStatus:'pending',paymentReference:'',paymentProof:'',paymentSubmittedAt:null,paymentVerifiedAt:null,paymentRejectedAt:null,status:'Payment Required',fileStructure:structure,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});const attachments=[];for(let i=0;i<imgs.length;i++){show(`Processing design ${i+1} of ${imgs.length}...`);const d=await compressImage(imgs[i]);attachments.push({filename:d.name,content:d.content.split(',')[1],contentType:d.type});await setDoc(doc(db,'projects',ref.id,'designs',String(i+1)),{name:d.name,type:d.type,size:d.size,content:d.content,createdAt:serverTimestamp()})}show('Sending project notification...');const email=await fetch('/api/send-project',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({projectId:ref.id,clientName,clientEmail:currentUser.email,projectName,package:packageName,price,requirements,attachments})});let emailData={};try{emailData=await email.json()}catch{}if(!email.ok){throw new Error(emailData?.error?.message||emailData?.error||'Project created, but the admin email could not be sent.')}location.href=`payment.html?id=${encodeURIComponent(ref.id)}`}catch(err){console.error(err);show(err.message||'Something went wrong.',true);btn.disabled=false}};
